### ISSUE TITLE
Optimized shadows on leaves break bushy resource packs

### ISSUE THREAD

**Issue by owosoup** [ComplementaryDevelopment/ComplementaryReimagined#10]
I use the vanillatweaks bushy leaves pack with my textures, and the leaves get dark if shadow quality is at medium or low.
I suppose it's the new "optimized shadows on leaves" :
>With low and medium shadows:
![2023-02-26_14 19 24](https://user-images.githubusercontent.com/95828007/221413629-d7d8861c-6d0e-438d-9256-e3515c6c075e.png)
>With high shadows:
![2023-02-26_14 19 37](https://user-images.githubusercontent.com/95828007/221413634-cdc646f0-7d2c-4178-8ebb-b0d23ad1f35b.png)

**Comment by EminGT** [comment]
This is a known sacrifice of the Medium and Low quality shadows. It unfortunately can't be fixed without removing the optimisation completely
