### ISSUE TITLE
How to disable the drowned glow?

### ISSUE THREAD

**Issue by TheCrossCarrier** [ComplementaryDevelopment/ComplementaryReimagined#101]
Hello guys!
How to disable the drowned glow in shader settings?

Thanks a lot! <3

**Comment by EminGT** [comment]
We shouldn't add individual settings for disabling glow on the hundreds of things that glow in this pack. What you can do instead is opening the "shaderpack files" -> "shaders" folder -> open "entity.properties" with notepad -> delete "drowned" from there
