### ISSUE TITLE
[Suggestion] Add raytraced reflections

### ISSUE THREAD

**Issue by bahillybeans** [ComplementaryDevelopment/ComplementaryReimagined#102]
I've been trying to take a screenshot of a lake but the reflection gets cut off at the side due to the fact that the reflections are screen-space. I'm just trying to take a screenshot to use as my background but i cant because the reflections aren't good.

**Comment by Karpatok9089** [comment]
It would make a heavy performance inpact and GTX graphics cards arent gonna like it.
The best soultion would be that the water still uses screen-space reflections and the other areas should use some kind of reflection calculation instead. Or something like the Watershader mod used in b1.7.3

**Comment by EminGT** [comment]
The current reflections are already ray traced. They are screen-space ray traced. World space reflections are something I want to implement sooo much but they are also so hard to get right that every single one of my experiments failed to look acceptable. Maybe one day
