### ISSUE TITLE
[Suggestion] Add player self reflections

### ISSUE THREAD

**Issue by Karpatok9089** [ComplementaryDevelopment/ComplementaryReimagined#103]
It would be nice to have player self reflections in first person mode on blocks, like water, reflective blocks, etc.
It can be disabled if not needed for like screenshots.
![2024-05-13_16 24 40](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/110969697/e7a33996-7a1a-4e2a-a045-6c9bd589ae83)
Image from a b1.7.3 Watershader mod

**Comment by DarianLStephens** [comment]
That mod needs to come back. Or Iris at least needs the ability to create a reflection surface that shaders can use, which actually renders the world from the correct perspective.

**Comment by EminGT** [comment]
The "Watershader mod" has access to CPU side stuff that Complementary doesn't. It's simply way too problematic to do this on completely GPU side
