### ISSUE TITLE
Fuzzy appearance at light/shade border

### ISSUE THREAD

**Issue by TrousleInTheDesert** [ComplementaryDevelopment/ComplementaryReimagined#104]
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/110197171/71ed925a-f336-4570-902b-7475d4b0e345)
Sorry Im new to shaders and all the settings don't mean much to me.

Im using **embeddium**-0.3.18+mc1.20.1-all and **oculus**-mc1.20.1-1.7.0 for shaders. I have a few **performance mods** like memoryleakfix-forge-1.17+-1.1.5, modernfix-forge-5.17.0+mc1.20.1, CullLessLeaves-Reforged-1.20.1-1.0.5, dynamic-fps-3.4.3+minecraft-1.20.0-forge.

![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/110197171/0ddf5600-43d1-46fa-830b-131a917818d5)

**Comment by EminGT** [comment]
It just looks like you disabled TAA / Temporal Filtering
