### ISSUE TITLE
Sometimes CR breaks when Distant Horizons is enabled | 1.20.6

### ISSUE THREAD

**Issue by sanshz** [ComplementaryDevelopment/ComplementaryReimagined#107]
When I try to enable CR (with DH enabled) I get following error
```
dh_terrain.fsh: dh_terrain.fsh: 0(359) : error C1503: undefined variable "dhProjection"
0(360) : error C1503: undefined variable "dhProjectionInverse"
```
Though I am able to make it work (not sure how this works), basically i just load Bliss or BSL shader first then I use CR.

![2024-06-20_14 03 36](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/53253706/4519e7d0-6112-4b5d-b7fc-a6540034d1de)

![2024-06-20_14 05 01](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/53253706/503dee56-34af-4f44-b2bb-f9c80061f20a)

This does work but it is still annoying to first load other shaders then the one I want to use.
(If this is something I should report to DH, please let me know)

**Comment by EminGT** [comment]
It's because you are messing with the DH settings. Changing any DH settings can break the shader pipeline of Iris. This is unrelated to Complementary
