### ISSUE TITLE
Custom command block textures keep original texture's glow area, even with custom emissive textures.

### ISSUE THREAD

**Issue by Kennylotl** [ComplementaryDevelopment/ComplementaryReimagined#11]
When a command block has been retextured, giving it custom emissive textures is extremely limited because any colored pixels will be glowing if they are in the original 5x5 pixel area that the vanilla command block textures lights are in.
Vanilla:
![image](https://user-images.githubusercontent.com/127928680/225237638-f9656078-84a5-4a8a-b458-af5411637843.png)
[Resource pack](https://www.planetminecraft.com/texture-pack/better-command-blocks/):
![image](https://user-images.githubusercontent.com/127928680/225237665-51591a8c-a7c7-446c-92b2-d1355fc258c8.png)
Example of affected area:
![image](https://user-images.githubusercontent.com/127928680/225237684-b6d3d48b-bfa3-475e-abd1-0cffd232da0c.png)
(Example images do not use emissive textures for clearest demonstration)
When this glowing is paired with emissive textures another issue is made apparent: The built-in glowing textures animations seem to not interpolate at all, which leads to vast inconsistency when used with custom textures that do interpolate.

Potential solution A: Add option to automatically disable glowing for blocks or textures that have emissive textures in enabled resource packs
Potential solution B: Add a config option to disable glowing on individual blocks or textures
Potential solution C: Solutions A & B together, which could automatically work in all applicable situations but could be enabled or disabled per block/texture

(Running ComplementaryReimagined_r2.0.2 on fabric with iris, sodium, indium, etc on minecraft 1.19.3)

**Comment by EminGT** [comment]
Will be fixed in the next release

**Comment by tworoundthings** [comment]
Still an issue on v5.3 
![image](https://github.com/user-attachments/assets/3739f57e-5704-49cc-a8f0-f0ad210702ac)

**Comment by EminGT** [comment]
> Still an issue on v5.3

That screenshot has nothing to do with this issue. The problem mentioned here is the glow area being too restrictive, and it has been fixed
