### ISSUE TITLE
Add Option to Make Players Emit Light

### ISSUE THREAD

**Issue by JamieBra** [ComplementaryDevelopment/ComplementaryReimagined#110]
Would it be possible to add a feature to make players emit light regardless of held item? Or to make certain armor trims or shields emit light so that you do not always need to hold a torch in order to see? While it is possible to just turn up the brightness of the game, it would be ideal to have an option to always make players emit light so that you can use shields or other off-hand items when you need to see. The current system can make it clunky to fight in dark areas or explore properly as you frequently have to switch either your off-hand light sources with shields or blocks. This prevents you from utilizing the off-handed system in a more convenient way without the game becoming really dark in certain situations.

**Comment by EminGT** [comment]
Sorry I'm not keen on adding this. It will make a lot of scenes look worse with the added light, it won't make sense, and I find having to choose between a shield and torch to be a cool gameplay challenge. You could maybe pass this suggestion to Euphoria Patches which is a an add-on for Complementary that is less restrictive with its setting additions
