### ISSUE TITLE
Advanced colored lighting breaks the world border.

### ISSUE THREAD

**Issue by DarkRTA** [ComplementaryDevelopment/ComplementaryReimagined#111]
When using the option for advanced colored lighting, the world border fails to render correctly.

I am using a Radeon RX 5600 XT on an Arch Linux machine if this is of any relevance.

With colored lighting disabled:
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/15368682/32a2f0c3-6562-4ee3-9ef9-d78ab805c4ae)

With colored lighting set to 6 chunks:
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/15368682/1579df0f-72e1-4f8a-bdd0-b88422d761bf)

**Comment by EminGT** [comment]
I can't reproduce this problem unfortunately. Maybe try without any mods?
