### ISSUE TITLE
Instant crash when using the latest Distant Horizons release (mc 1.21)

### ISSUE THREAD

**Issue by glugau** [ComplementaryDevelopment/ComplementaryReimagined#112]
In Minecraft 1.21, without Distant Horizons, the shader runs fine. As soon as I add the mod however, if I enter any map, the game immediately crashes with the following error message:
```
The game crashed whilst unexpected error
Error: java.lang.NoSuchFieldError: Class com.seibel.distanthorizons.api.methods.events.abstractEvents.DhApiBeforeBufferRenderEvent$EventParam does not have member field 'com.seibel.distanthorizons.coreapi.util.math.Vec3f modelPos'
```

**Comment by EminGT** [comment]
That can't be a shader issue. That's literally a Java error. Shaders are completely run on GPU side and don't have absolutely anything to do with the Java side of the game. That's a problem between DH and the shader loading mod (Iris/Optifine/Oculus)
