### ISSUE TITLE
Weird lighting on Bushy Leaves

### ISSUE THREAD

**Issue by Soabac** [ComplementaryDevelopment/ComplementaryReimagined#116]
hello so i don't know if there's a fix for this but i play using a bushy leaves texture pack but with complementary it creates some weird shadows, id like to know if there's a possibility to make it less jarring
here's what i mean:
![2024-07-18_13 17 57](https://github.com/user-attachments/assets/3a0b4a87-8311-4e37-8d7f-237036518429)

thanks for your time !

**Comment by EminGT** [comment]
Just go to Video Settings -> Shaders Menu -> Shader Settings -> Performance -> and set Shadow Sample Quality: High

**Comment by Soabac** [comment]
not ideal for my fps count but thanks
