### ISSUE TITLE
Wrong Clouds

### ISSUE THREAD

**Issue by Karpatok9089** [ComplementaryDevelopment/ComplementaryReimagined#117]
I don't know that I enabled some kind of setting, but the clouds has some stripes in it.
![2024-07-20_17 06 06](https://github.com/user-attachments/assets/553dd30e-a895-40af-9b7d-418f7cef66a0)

Config file: 
[ComplementaryUnbound_r5.2.2 + EuphoriaPatches_1.3.2.txt](https://github.com/user-attachments/files/16321497/ComplementaryUnbound_r5.2.2.%2B.EuphoriaPatches_1.3.2.txt)
(This is an Euphoria Patches config (Bug also applies there), but applying it to regular Complementary still makes the bug appear)

Mods: 
![image](https://github.com/user-attachments/assets/f31e090e-bd59-4e13-be62-e06901fa5af4)

**Comment by Karpatok9089** [comment]
Disabling every mod except sodium and iris still gives me weird clouds
![2024-07-20_17 39 24](https://github.com/user-attachments/assets/21837113-e3c1-400e-ab24-0eadaab32364)

**Comment by jgoro** [comment]
I had this issue before. It was caused by anisotropic filtering being force applied to Minecraft through Nvidia settings.

**Comment by EminGT** [comment]
Open Nvidia Control Panel -> 3D Settings -> Set "Anisotropic Filtering" to "Let application decide"

**Comment by Karpatok9089** [comment]
Looks like that it did fix the clouds and inproved performance too. Thanks!
