### ISSUE TITLE
[Suggestion] Make texts glow!

### ISSUE THREAD

**Issue by 70CentsApple** [ComplementaryDevelopment/ComplementaryReimagined#118]
New [Text Display Entity](https://minecraft.wiki/w/Display) and name labels, etc., seems too dark when it's night.
![img](https://github.com/user-attachments/assets/231bd913-d269-4a7b-9f64-c12c74eb1879)

Could there be an option to make those texts **glow** when they render? I suppose it will be good to offer an option for users to toggle, and I will quite appreciate it.

Edit: I found that how you dealt with sign text seems good, perhaps we can reuse these codes?
https://github.com/ComplementaryDevelopment/ComplementaryReimagined/blob/main/shaders/lib/materials/specificMaterials/others/signText.glsl

**Comment by EminGT** [comment]
The problem is that we can't detect entity texts

**Comment by 70CentsApple** [comment]
> The problem is that we can't detect entity texts问题是我们无法检测实体文本

How about name labels? Is that possible?

**Comment by EminGT** [comment]
Same thing. They are just a passenger to the usual lighting. We can't give them special handling
