### ISSUE TITLE
Double quartz slabs not reflective in IPBR on MC1.12.2

### ISSUE THREAD

**Issue by jgoro** [ComplementaryDevelopment/ComplementaryReimagined#119]
Quartz slabs are reflective with Integrated PBR+ but not reflective when there are two stacked to look like a normal quartz block.

**Comment by EminGT** [comment]
In which version of Minecraft?

**Comment by jgoro** [comment]
1.12.2

**Comment by EminGT** [comment]
Will be fixed in Complementary r5.3
