### ISSUE TITLE
Other players mirror my player's animations

### ISSUE THREAD

**Issue by AntxiCrafter** [ComplementaryDevelopment/ComplementaryReimagined#122]
For some reason when I use Complementary Shaders if I crouch my friend's player crouch. If I equip a crossbow my friend also makes the animation of equiping crossbow. I tested and this only happens with Complementary. If I change shaders or disable them the error ceases to exist.
![2024-07-24_23 56 41](https://github.com/user-attachments/assets/c2a4214e-e1ca-45e8-b3a4-6f8aa65701f4)
In this Image I am the one crouching, but for some reason my friend also makes the same animation.

![2024-07-24_23 56 56](https://github.com/user-attachments/assets/b3bafa33-05f9-464e-9a39-85c5471f6283)
Here I have the crosbow equiped and my friend also makes the same animation.

![2024-07-24_23 57 07](https://github.com/user-attachments/assets/baa770fb-7d92-49a8-b86d-6efadc44505f)
Here I use a bow and my friend even if he's afk his player mimics my same animation

Im using mods so it may be some mod doing this errors, but the fact that it only hapens when using Complementary made me decide to still open an issue here

**Comment by EminGT** [comment]
Sorry there is absolutely 0% chance this is a Complementary issue. Shaders can not do this even if I were to spend years trying to do it. This is clearly an issue between mods. It may involve the shader loader mod if it only happens with specific shaders.
