### ISSUE TITLE
SSS doesn't work on tall_grass

### ISSUE THREAD

**Issue by G1ll0u** [ComplementaryDevelopment/ComplementaryReimagined#124]
Hello,

Here's a new problem report ! :

As you can see below, SSS doesn't render on grass with v5.2.2 on Optifine 1.12.2 :
![image](https://github.com/user-attachments/assets/5df015ac-8a34-4498-8e7c-6cec605659ff)

For example, SSS works on fern and double_plant but nothing for tall_grass, tree foliage and better grass generated by BetterFoliage mod. Even with BetterGrass disabled.
It only works on specific blocks like some flowers or double_plant.

PS: I disabled BetterFoliage by removing the mod (instead of disabling it in its settings) and it still doesn't work.
              Oh, and SSS works perfectly in 4.7.2

See you !

**Comment by EminGT** [comment]
Modded grass won't have SSS. That's completely expected. v4.7.2 used to have a ton of mod IDs built in but that proved to be a task way too big for a single developer so I no longer put modded IDs in the pack. You can put them in yourself by opening the shader files -> shaders -> block.properties file using notepad, and add the modded grass IDs accordingly

**Comment by G1ll0u** [comment]
Oh yes I'll give it a shot.

Thanks !

**Comment by G1ll0u** [comment]
I FOUND IT !

To fix that we have to assign the leaves and grass ID according to shader.properties (block.10005 and block.10009) from the current shaderpack in betterfoliage.cfg.
```
shaders {
    I:leavesId=10xxx
    I:grassId=10xxx 
}
```
it can be done in game in F8 betterfoliage's menu.
