### ISSUE TITLE
Create contraptions look wrong when seuspbr/labpbr is enabled and a texture pack is used

### ISSUE THREAD

**Issue by pfgithub** [ComplementaryDevelopment/ComplementaryReimagined#126]
Using Complimentary Reimagined r5.2.2 and resource pack [AVPBR Retextured](https://modrinth.com/resourcepack/avpbr-retextured)

Mods: Create Mod, Oculus, Iris & Oculus Flywheel Compat

With labpbr: (weird broken stuff)

![2024-08-04_18 05 41](https://github.com/user-attachments/assets/c814a289-6c73-4567-968c-cc1cc88cfb72)

Without labpbr:

![2024-08-04_18 05 52](https://github.com/user-attachments/assets/24b469bf-d5fe-4f79-ac54-11ab5bff12b4)

Patch to disable labpbr for just block entities to fix it;

```diff
// gbuffers_block.glsl
#include "/lib/common.glsl"

+ #define RP_MODE 1
+ #undef CUSTOM_PBR
+ #undef POM
+ #define IPBR
+ #undef PBR_REFLECTIONS
+ #undef TEMPORAL_FILTER
```

I'm not sure how to implement that without the duplication but it does work

It would be nice to have an option to use calculated pbr just for block entities to fix that, or fix the problem somehow so it works with create. I'm assuming it's because create is using vanilla textures for its block entities and the calculations don't work right because they're transformed or something?

**Comment by EminGT** [comment]
This is caused by "Iris & Oculus Flywheel Compat". Only they can fix it
