### ISSUE TITLE
Lighting issue caused by using shader with Continuity

### ISSUE THREAD

**Issue by davidkochprg** [ComplementaryDevelopment/ComplementaryReimagined#128]
While using connected textures through the Continuity mod in conjunction with a resource pack that adds a 2D texture to a 3D block like bushy leaves for example, Complementary Shaders don't correctly apply the ambient/sun lighting to the textures added by the resource pack, example in the first image. 

As you can see in the second image, a direct light source applies to the newly added textures correctly. Disabling connected textures gets rid of this issue entirely as seen in the third image.

I submitted this as an issue here as other shaders I tested don't seem to have this problem.

|![1](https://cdn.discordapp.com/attachments/1215375267435122711/1274387713981677631/2024-08-17_17.20.30.png?ex=66c2118b&is=66c0c00b&hm=003b6672354b97724e44d276594327a54ad35c584624b1b869fd2436c29eb3c1&)|![2](https://cdn.discordapp.com/attachments/1215375267435122711/1274388298982228028/2024-08-17_17.23.11.png?ex=66c21217&is=66c0c097&hm=67410f408461862c9ed4e55b31fb938776d36a80ffc025b052879ffed3682025&)|![3](https://cdn.discordapp.com/attachments/1215375267435122711/1274388309254340671/2024-08-17_17.23.26.png?ex=66c21219&is=66c0c099&hm=3b3db593209426e86fb5be1af5e46eb8eebf531f1b675c15377a3c2caaf6a5c1&)|![4](https://cdn.discordapp.com/attachments/1215375267435122711/1274388326169837650/2024-08-17_17.23.46.png?ex=66c2121d&is=66c0c09d&hm=d9422bef76b2675d5138b3c3be3473254d226587566b1487c88e0c85dfab6536&)|
|-|-|-|-|
|Complementary with CTM|Complementary with CTM + Point light|Complementary without CTM|Other shader with CTM|

---

> Iris **1.7.3**
> Complementary Reimagined **r5.2.2**
> Continuity **v3.0.0-beta.5**

**Comment by EminGT** [comment]
You simply need to go to Shader Settings and set "Shadow Sample Quality" to "High" or above

PS: The "Shadow Sample Quality" setting will be renamed to "Real Time Shadows" in the next update
