### ISSUE TITLE
Rain Puddles not showing at all

### ISSUE THREAD

**Issue by dAKirby309** [ComplementaryDevelopment/ComplementaryReimagined#129]
Tested on r5.1.1 and r5.2.2 
For some reason no puddles render on the ground at all when raining despite the setting being enabled. I've tried on my .minecraft and a fresh .minecraft with Iris. Version 1.19.0 and I've played around with many different settings.

Shader settings:
[ComplementaryReimagined_r5.2.2.zip.txt](https://github.com/user-attachments/files/16646556/ComplementaryReimagined_r5.2.2.zip.txt)

Example:
![image](https://github.com/user-attachments/assets/5a79717f-f979-40da-94c6-1096a00c056a)

**Comment by EminGT** [comment]
Try setting the "Profile" to High or above

**Comment by dAKirby309** [comment]
> Try setting the "Profile" to High or above

Nah that isn't the issue. I figured it out. The issue was that I needed to update my Iris and Sodium mods. They were slightly outdated to support rain puddles and colored lighting properly.
