### ISSUE TITLE
BossBar fog does not show with shader

### ISSUE THREAD

**Issue by ShaneBeee** [ComplementaryDevelopment/ComplementaryReimagined#131]
I noticed that BossBar fog does not show in the shaders.

Minecraft version:  1.21.1
shader version:
<img width="422" alt="Screenshot 2024-08-23 at 4 18 46 PM" src="https://github.com/user-attachments/assets/9171c43c-4ebc-442a-b17a-3149a33bb0a7">
Iris version:
<img width="346" alt="Screenshot 2024-08-23 at 4 26 33 PM" src="https://github.com/user-attachments/assets/c797b0e8-35bc-4e72-a8e3-132c9dfb05cf">
Let me know if there's any other information you need.

no shader - no fog:
<img width="966" alt="Screenshot 2024-08-23 at 4 17 25 PM" src="https://github.com/user-attachments/assets/56e61a19-564c-422b-882a-cdf36d463aef">

no shader - with fog:
<img width="966" alt="Screenshot 2024-08-23 at 4 17 12 PM" src="https://github.com/user-attachments/assets/d683d17c-759c-4822-a488-52a7e51183ce">

shader - no fog:
<img width="966" alt="Screenshot 2024-08-23 at 4 17 53 PM" src="https://github.com/user-attachments/assets/94a6103e-e4de-4c25-a365-5d22a34c9e95">

shader - with fog:
<img width="966" alt="Screenshot 2024-08-23 at 4 18 03 PM" src="https://github.com/user-attachments/assets/b7866ed3-8e20-41f3-be16-9fd5e01c19ca">

**Comment by EminGT** [comment]
I can't fix this without finding a way to somehow get the vanilla fog paramaters to work perfectly with Complementary's fog system. So it's going to stay like this until I think of a way to manage that
