### ISSUE TITLE
Random blocks are treated like leaves, causing unintentional waving through OptiFine

### ISSUE THREAD

**Issue by colindevick** [ComplementaryDevelopment/ComplementaryReimagined#132]
Blocks like the crafting table or dirt will have a seemingly random side wave as if it were a leaf block.
I have confirmed this by shutting off the waving setting and waving for the issue blocks stopped when turning off leaf waving.

**Comment by EminGT** [comment]
This is an old Optifine problem. Restarting the game makes random other blocks act like leaves instead. There is nothing I can do to fix this
