### ISSUE TITLE
Official Twilight Forest Support

### ISSUE THREAD

**Issue by Alyaqdhans** [ComplementaryDevelopment/ComplementaryReimagined#133]
The Twilight Forest has been an old main dimension in modded Minecraft for years now, and I think it's the 4th dimension for Minecraft of how well known it's. For that, I think it's a great idea to add support for it in the famous Complementary shader.

Currently, when using the shader it ruins Twilight Forest's beautiful dark sky with bright sunset lighting. Also, if the new Twilight aurora is preserved it will add to Twilight Forest's atmosphere.

Screenshots:
![Screenshot (586)](https://github.com/user-attachments/assets/fff5a899-e8fd-4c1c-bdf5-71c424f8e8e5)
![Screenshot (587)](https://github.com/user-attachments/assets/e7ec9495-39d3-488d-b2c3-fb9ee3b2bf54)

Here is a video of how the new Twlight arura looks:

https://github.com/user-attachments/assets/0401f2a6-c1f3-4afa-9ad6-b3b4bbd040ad

**Comment by EminGT** [comment]
I don't do specific modded dimension support anymore because of many reasons that would take me to explain all. If one day I change my mind, Twilight Forest will be near the top of the list
