### ISSUE TITLE
"Show light level" not working

### ISSUE THREAD

**Issue by Squtzy** [ComplementaryDevelopment/ComplementaryReimagined#135]
Hi. 
Noticed when I came back to minecraft that the "show light level" option is not working anymore and is not showing the light levels, previously been using it with the "When holding light source" but tried the different ones. Also tried turning it off completely and then back on with the same result.

Steps to reproduce: 
Open "other settings" in Shader settings
Enable "Show light level"
Not displaying light level like setting intends to do.

Adding screenshots to display setting being enabled and no light level being displayed.
![2024-09-14_14 36 19](https://github.com/user-attachments/assets/4c7ab8da-f2c8-4a0f-8fc7-87ecdfc12d31)
![2024-09-14_14 35 26](https://github.com/user-attachments/assets/00ab68aa-3d9c-4331-a4b2-13c3a1785bf0)

**Comment by EminGT** [comment]
An Iris update broke it. Will be fixed in an Iris update or the next Complementary update (r5.3)

**Comment by Squtzy** [comment]
> An Iris update broke it. Will be fixed in an Iris update or the next Complementary update (r5.3)

Oh I see, thanks for the info :)
