### ISSUE TITLE
Incompatible with the latest version of Distant Horizons

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [ComplementaryDevelopment/ComplementaryReimagined#136]
Complementary `v5.2.2`
Distant Horizons `2.2.1-a-1.21.1`
also tried latest dev dh, same bug

vanilla cloud still appeared
<img width="1577" alt="image" src="https://github.com/user-attachments/assets/5b33ca61-e13c-49d4-bb11-e2dfb5fd7640">
<img width="1376" alt="image" src="https://github.com/user-attachments/assets/de6ffd8d-24ee-4dfa-9c55-1da8d41e6dc0">

**Comment by EminGT** [comment]
You can turn off the DH clouds in DH settings. But I'll disable them in the next update myself anyways
