### ISSUE TITLE
[Feature Request]Add lighting color temperature or RGB value setting

### ISSUE THREAD

**Issue by Mikeyzy** [ComplementaryDevelopment/ComplementaryReimagined#137]
Can we have a setting for lighting color of Sun, Moon, and light sources, either in light temperature or RGB values. Not everyone enjoy the default orange toned lighting color.
Examples of adjustable light color shaderpacks:
Pixel Perfect Shaders (color temperature)
![image](https://github.com/user-attachments/assets/98d1cb0f-62ca-4664-ac46-feb41f32e2bb)
Sildur's Vibrant shaders (RGB value)
![image](https://github.com/user-attachments/assets/eff2878d-e3f5-48e0-a06d-99767f5dd1b0)

**Comment by EminGT** [comment]
No, sorry. The existing settings are good enough
