### ISSUE TITLE
Handheld Light Color

### ISSUE THREAD

**Issue by Barujin** [ComplementaryDevelopment/ComplementaryReimagined#138]
With ACL turned on, the color of the handheld light is intense, regardless of changing colored light intensity in Other. I wish it changed along with placed light blocks.

**Comment by Barujin** [comment]
BTW, I'm using Iris with 1.21.1.

**Comment by EminGT** [comment]
Sorry for being late but I can't reproduce this problem. Can you send a couple screenshots maybe?
