### ISSUE TITLE
Hand held dynamic light appears to just create a light source at camera?

### ISSUE THREAD

**Issue by nopeless** [ComplementaryDevelopment/ComplementaryReimagined#14]
I'm not sure if this is a bug or a feature, but the `Shader handheld light` option seems to create a lightsource at the camera, not the location where the hand is. 

This is very obvious in perspective mode.

Can I have a comment on this? Thanks in advance

**Comment by EminGT** [comment]
Hello. Unfortunately, there is no way to know where the player is in a Minecraft shaderpack, so we need to use the camera position as the center. Optifine and Iris need to give shaders additional information to fix this problem. But thank you for taking your time to write this to me
