### ISSUE TITLE
Wrong sky in custom named worlds

### ISSUE THREAD

**Issue by NonSwag** [ComplementaryDevelopment/ComplementaryReimagined#140]
Worlds with custom namespaces for nether and end dimensions render the sky from the overworld

In these examples I named the worlds to worlds:end and worlds:nether as seen in the debug screen
![2024-10-06_08 22 49](https://github.com/user-attachments/assets/1e8ceff3-3f45-43cb-a5e9-c4f5e512f1b9)
![2024-10-06_08 24 22](https://github.com/user-attachments/assets/5bd5f99d-b4a9-47f1-b57b-52c2c8703c1c)

**Comment by EminGT** [comment]
This is just how Iris handles dimensions. It's not something I can change
