### ISSUE TITLE
The nether is blindingly bright

### ISSUE THREAD

**Issue by sethCodesSometimes** [ComplementaryDevelopment/ComplementaryReimagined#141]
overworld with complimentary
![Screenshot from 2024-10-10 16-07-33](https://github.com/user-attachments/assets/e154fb9c-ddae-4de1-b882-40044071adc5)

nether with complimentary (very bright and wrong colours)
![Screenshot from 2024-10-10 16-07-53](https://github.com/user-attachments/assets/4c74746f-5d41-480b-abc5-51d1bf54bc6f)

nether with bliss (normal colours, not bright)
![Screenshot from 2024-10-10 16-08-07](https://github.com/user-attachments/assets/b9c4562a-b37d-4365-a8a4-4ebde54d425d)

nether with BSL (normal again)
![Screenshot from 2024-10-10 16-08-17](https://github.com/user-attachments/assets/94fbb46c-c1cf-4ada-b1ac-77681fc2da20)

**Comment by Arceus-77** [comment]
What mods do you have, it also could be settings, it looks like the colors were inverted.

**Comment by EminGT** [comment]
Closing as there isn't enough information to suggest this is a shader problem. I would like to remind readers that a problem only being visible on some shaders and not being visible on some other shaders does not mean that problem is the shader's fault.
