### ISSUE TITLE
Compat with Securitycraft

### ISSUE THREAD

**Issue by Arceus-77** [ComplementaryDevelopment/ComplementaryReimagined#144]
When I use Complementary, and I build a bunker, in case my sister, summons the wither storm. I use the reinforced blocks from security craft, but rather than look pretty with the shader, they look like the vanilla version, fake water looks like water without the shader. could you fix this.
P.S how do I use the labels

**Comment by EminGT** [comment]
Nothing to do other than adding the block IDs next to their vanilla counterparts in the block.properties file inside the shaderpack. I don't do this myself because there are a million mods out there, but you can do it yourself
