### ISSUE TITLE
The deputy holding the light source will cause some monsters and chickens to glow abnormally.

### ISSUE THREAD

**Issue by XueTwelve** [ComplementaryDevelopment/ComplementaryReimagined#150]
![image](https://github.com/user-attachments/assets/02c9ac56-f0c2-4999-bc38-c605ef94d440)
![image](https://github.com/user-attachments/assets/9b9af936-3eac-4945-bc2d-35e8f696a5a5)

**Comment by EminGT** [comment]
This is a problem between the shader loader mod and other mods you are using
