### ISSUE TITLE
Complementary Shaders v.4 visual bugs 

### ISSUE THREAD

**Issue by ThatRdude** [ComplementaryDevelopment/ComplementaryReimagined#151]
Hi, I noticed when I was playing Minecraft 1.21 with my favorite shaders Complemantary v.4, that there were a few graphical bugs: 
-Clouds not getting proper lighting during daytime with Vanilla clouds enabled. 
-Grass not getting proper lighting during daytime as well.

Is this perhaps a driver issue? Because these bugs apply to all v.4 versions. Could this maybe be fixed, because a lot of popular creators like Gorillo and Blockical still use v.4 in 1.21-1.21.3? 

If it's somehow not possible to update all driver versions,? if not could you at least provide some settings in the Unbound shaders, that enable all the features that v.4 had?

Thank you for your understanding

**Comment by EminGT** [comment]
Complementary v4 is superseded by r5. There isn't a good reason for me to spend any time updating v4 when pretty much everyone that used both packs the same amount of time prefers r5. The people still using v4 mostly just consist of people that don't know the setting r5 provides.

**Comment by ThatRdude** [comment]
Oh, okay sorry for bothering you, thanks for the clarification
