### ISSUE TITLE
Command block textures are always emissive

### ISSUE THREAD

**Issue by tworoundthings** [ComplementaryDevelopment/ComplementaryReimagined#153]
Still an issue on v5.3 
![image](https://github.com/user-attachments/assets/3739f57e-5704-49cc-a8f0-f0ad210702ac)

_Originally posted by @tworoundthings in https://github.com/ComplementaryDevelopment/ComplementaryReimagined/issues/11#issuecomment-2464686652_

**Comment by EminGT** [comment]
This is a "works as intended" situation. IntegratedPBR is specifically made for the vanilla textures. You should either change the "RP Support" setting to something other than IntegratedPBR, or you can open the shader files, find "block.properties" and delete command block IDs from there
