### ISSUE TITLE
Weird Stripes on ground and no shadows on Leaves

### ISSUE THREAD

**Issue by Eglijohn** [ComplementaryDevelopment/ComplementaryReimagined#154]
I have weird dark Lines/Shadows on the ground and shadowns are not correctly renddered on leaves 
This is only at day, in the night everything seems fine
Im using Complementary Reimagined r5.3 on 1.21

[Screenshot](https://media.essential.gg/04de1fc2-4d7f-4a02-d40d-e2a518117c00)

**Comment by EminGT** [comment]
You probably just need to update your Iris to the latest version

**Comment by Eglijohn** [comment]
Okay ill try it

**Comment by EminGT** [comment]
Closing I assume the problem was Iris related
