### ISSUE TITLE
Translation of Complementary Shaders into Ukrainian

### ISSUE THREAD

**Issue by StarmanMine142** [ComplementaryDevelopment/ComplementaryReimagined#155]
Would it be possible for you to add the Ukrainian translation created by me to your Shader pack?

Download in .lang format on mediafire: https://www.mediafire.com/file/cpkxi5es5wxgw96/uk_UA.lang/file

It must be placed in shaders\lang (it should be in «lang» next to «en_US.lang»)

**Comment by EminGT** [comment]
Thank you for taking your time to do this but I'm sorry to inform you that I don't take any setting translations at the moment. You could probably send this to Euphoria Patches though. It's a mod that adds more stuff to Complementary
