### ISSUE TITLE
Water reflections for Distant Horizons don't behave correctly

### ISSUE THREAD

**Issue by tractorbeam0** [ComplementaryDevelopment/ComplementaryReimagined#156]
The reflection seems to act as if the camera is always at sea level. This may apply to PBR and other reflections, I don't know for sure though. I'm no shader dev, but I've made enough computer software to know that this might be an easy fix, like plugging in a reference to the player's y coord in some equation somewhere.

Camera at water level (it looks right this way)
![Screenshot_20241111_132925-1](https://github.com/user-attachments/assets/5a932fcc-4cb6-4bdc-832f-15ecd4b50920)

Camera risen a little (uh oh?)
![Screenshot_20241111_133055](https://github.com/user-attachments/assets/67963e0a-d3a0-4b6b-8d94-5ba0b4ad85e2)

Camera risen a lot (yeah that's not right)
![Screenshot_20241111_133207](https://github.com/user-attachments/assets/8db541e0-6d45-4e6f-bf85-8112845a8e20)

**Comment by tractorbeam0** [comment]
After looking through dh_water.glsl, comparing it to the actual water shader and looking at GetReflection(), it is clear it's deliberately got a super simple reflection shader going on to lean into the whole purpose of the LODs, to enhance the view distance without compromising on performance.

While I certainly think this is the right direction, the implementation might have to be more complex than this. I would implement it myself if I knew what I was doing in the slightest with glsl (what the f*ck is a vertex shader? why does it have a main()? Why is it C? etc).

**Comment by EminGT** [comment]
Yeah this isn't an easy fix, and the only way to make them look better is to use actual ray tracing. So, sorry. I don't have any plan on improving this as Distant Horizons already runs much worse with shaders than most people expect it to
