### ISSUE TITLE
Dark leaves when there are blocks on any height one block on front of the leaves

### ISSUE THREAD

**Issue by OptionalNyx** [ComplementaryDevelopment/ComplementaryReimagined#158]
Minecraft version: 1.21.1 with fabric 0.16.9
Mods used: EuphoriaPatcher 1.4.3 r5.3
                   Iris 1.8.0 beta 8
                   Sodium 0.6.0 beta 4
Shader version: Complementary Reimagined r5.3

The instance used was fresh new, there was nothing modified, and I tried both the euphoria patcher version of the shader and the normal one. Using Ultra and very high fixes the issue.
This seems to happen only with leaves and only on the side that blocks are, even when the sun is facing the dark side of the leaves.
I already tried other shaderpacks, and the issue didn't happen on those. The leaves get darker if you use three blocks as in the image in any of the sides.

![2024-11-12_10 55 32](https://github.com/user-attachments/assets/da83cd78-4a7e-424a-883d-4e2ea43e2e0a)

**Comment by EminGT** [comment]
This is an optimization that is only enabled on lower Shadow Quality levels. Either increase Shadow Quality or Profile to get rid of it
