### ISSUE TITLE
The off-hand light causes the creature to render incorrectly.

### ISSUE THREAD

**Issue by XueTwelve** [ComplementaryDevelopment/ComplementaryReimagined#161]
In the latest version (which actually had this issue since the previous version), some brighter mobs would show up incorrectly when you were carrying a light source in your off-hand.
![2024-11-30_11 11 14](https://github.com/user-attachments/assets/c2e0f11b-14c1-4edd-8031-f7377699cccd)
![2024-11-30_11 11 15](https://github.com/user-attachments/assets/acef48f4-06e3-44fa-bf14-9bf570c593bc)
![2024-12-01_09 44 58](https://github.com/user-attachments/assets/f352241e-25aa-43cf-b4df-91f689d7bec5)
![2024-12-01_09 45 00](https://github.com/user-attachments/assets/893d1ecd-c0f1-42c6-ac70-85a4f2dec6dc)

**Comment by EminGT** [comment]
Yeah this really has more to do with the shader loader mod giving the shader wrong entity IDs. So I can't do anything about it
