### ISSUE TITLE
Sky color abruptly changes at times 13670 and 22331

### ISSUE THREAD

**Issue by Crossover661** [ComplementaryDevelopment/ComplementaryReimagined#162]
When the sky becomes dark in the evening, it gradually becomes darker, then suddenly and abruptly darkens at time 13670 (7:40:12 pm). As a result, the sky color at time 13669 is noticeably different from time 13670. This is also the time at which the sky light level reaches 4, its minimum.

The same thing happens in the early morning. When the time reaches 22331 (4:19:51 am), the sky suddenly starts to become bright. This is also the time when the sky light level increases from 4 to 5.

To reproduce:
/time set 13650
/gamerule doDaylightCycle true

You will see the an abrupt change in the color of the sky at time 13670, as though there is a "switch" that suddenly turns the daylight off. The apparent light level on the ground is unaffected.

I think the reason behind this is that this is the time when the shader changes its setting from "sunset" to "night".

Time 13669:
![2024-12-03_09 41 37](https://github.com/user-attachments/assets/47b8ab61-13ab-4150-ac2f-c434133333a9)

Time 13670:
![2024-12-03_09 41 44](https://github.com/user-attachments/assets/969a5659-760a-4412-ba02-7760185ee433)

**Comment by EminGT** [comment]
Yeah this is a problem I have known for a little while but it's good to have an issue report, so thank you. I will probably fix it soon

**Comment by EminGT** [comment]
Fixed in upcoming r5.4
