### ISSUE TITLE
Botania weapons/tools have broken visual on inventory UI

### ISSUE THREAD

**Issue by MNS26** [ComplementaryDevelopment/ComplementaryReimagined#164]
This seems only for the weapon items as far as i can tell
Other players do look fine holding their swords/other tools (from botania)

![image](https://cdn.discordapp.com/attachments/1247245010156388573/1314012639667421234/image.png?ex=67523922&is=6750e7a2&hm=7eab419fe608b1b09ea39c598bc20a36f937149a97b0353a99ea7f961f1b92eb&)
![image](https://cdn.discordapp.com/attachments/1247245010156388573/1314016778434646076/image.png?ex=67523cfd&is=6750eb7d&hm=c61c0ec8ecf35cb5cea65b9837c824a25a786701adf26977e6e4364c66977de9&)
![image](https://github.com/user-attachments/assets/b3fe3326-0d53-497e-ba0d-28b842fe2687)

(Fixed the pylons by disabling shader option in botania client json)

**Comment by MNS26** [comment]
oh and luminizer sparks also dont show up

**Comment by EminGT** [comment]
Botania uses their own renderers that are incompatible with shaderpacks in general. I really can't do anything about majority of Botania incompatibilities unfortunately. Sorry :(

**Comment by MNS26** [comment]
aw damn... welp now i know.
