### ISSUE TITLE
Visual Bug during sunrise and sunset

### ISSUE THREAD

**Issue by kamiphobia** [ComplementaryDevelopment/ComplementaryReimagined#167]
Weird visual bug in 1.19.2

Sudden layer of "fog" appears and moves along with the angle of the sun and moon.
Only shows around sunset and sunrise, no clue what the cause is.
I am playing with mods like pluto, canary, saturn adn rhino. Though I havent been able to find a culprit

To reproduce:
/time set 11250

![image](https://github.com/user-attachments/assets/4771c625-2546-4a91-a338-8fcc350ba0ee)

**Comment by EminGT** [comment]
Thank you for letting me know
