### ISSUE TITLE
[1.8.9] Leaves with grass Xray with Optifine's Fast leaves

### ISSUE THREAD

**Issue by HowardZHY** [ComplementaryDevelopment/ComplementaryReimagined#17]
![2023-04-27_17 46 58](https://user-images.githubusercontent.com/96782166/234825957-b1ee41b8-4e26-4d77-872f-0e1e2f3cd19a.png)

**Comment by HowardZHY** [comment]
Can leaves be non transparent?

**Comment by HowardZHY** [comment]
Complementary and BSL also have this bug

**Comment by EminGT** [comment]
Set leaves to Fancy, and use the "Nicer Fast Leaves" resource pack by
VanillaTweaks.

**Comment by HowardZHY** [comment]
I don't think that resource pack is for 1.8.9

**Comment by EminGT** [comment]
Ah yeah, a similar resource pack could be done for 1.8.9 but I can't find one on the internet

**Comment by HowardZHY** [comment]
I tried the Nicer Fast Leaves 1.13 one and changed leaves png file name and it works. I still hope shaders can fix it.

**Comment by EminGT** [comment]
Good to hear. I can't fix it on the shader side as it would cost performance on fancy leaves, which most people use
