### ISSUE TITLE
Macaws stairs/bridges and decorative blocks lighting seems to be rendering in "Fast" lighting, not "smooth"

### ISSUE THREAD

**Issue by Jenexs** [ComplementaryDevelopment/ComplementaryReimagined#170]
Hard to describe so heres some photos. Basically with the macaws stairs and bridges mod, the lighting from torches seems to be rendered at "Fast" quality instead of smooth lighting. As well with "decorative blocks" supports have a untouched corner from floodfill lighting (last photo).
![2024-12-30_00 50 51](https://github.com/user-attachments/assets/e211a392-036d-462f-88cc-d9e87edc4408)
![2024-12-30_00 50 44](https://github.com/user-attachments/assets/2a4e0597-7abd-472d-887a-a6db5a178957)
![2024-12-30_00 50 36](https://github.com/user-attachments/assets/8b70ccee-1f4c-44a0-aa54-1c9f8ed64103)
![2024-12-30_00 51 21](https://github.com/user-attachments/assets/48b7bfa9-93b9-4f75-9a1b-825c2fa7983d)

**Comment by EminGT** [comment]
There are three different problems here, and I should say in front that you are out of luck. 😔

1) Lighting not being smooth is mostly just a mod problem that has nothing to do with shaders. You can turn off shaders and it will still look like that.
2) Advanced Colored Lighting doesn't support any modded blocks at all. This is especially a problem on non-solid blocks like all the ones in your screenshots. This can cause problems like incorrect and blocky light colors.
3) Advanced Colored Lighting can have a light color issue at some corners from time to time. But it's usually very rare so the previous problem might be making it worse.

In the end I'm sorry but none of these are something I can fix without making big sacrifices. Though you might take a look at the Euphoria Patches add-on for Complementary that tries to add more modded block support, which might fix at least one of the problems

**Comment by Jenexs** [comment]
> There are three different problems here, and I should say in front that you are out of luck. 😔
> 
> 1. Lighting not being smooth is mostly just a mod problem that has nothing to do with shaders. You can turn off shaders and it will still look like that.
> 2. Advanced Colored Lighting doesn't support any modded blocks at all. This is especially a problem on non-solid blocks like all the ones in your screenshots. This can cause problems like incorrect and blocky light colors.
> 3. Advanced Colored Lighting can have a light color issue at some corners from time to time. But it's usually very rare so the previous problem might be making it worse.
> 
> In the end I'm sorry but none of these are something I can fix without making big sacrifices. Though you might take a look at the Euphoria Patches add-on for Complementary that tries to add more modded block support, which might fix at least one of the problems


Would like to preface this isn't an argument, just trying to understand/learn here.

1/2. Bliss shaders has no issue with the modded blocks in their "flood fill", but the cave detection system is a bit of an annoyance hence moving to complementary. I assume this is a difference in how it's coded? Is there a possibility that putting these blocks into the block.properties file might fix the lighting? 

3. That's understandable, not a huge annoyance in the grand scheme of things. Looks like lighting is optimised for stairs/slabs at the most?

I'll look into the euphoria mod, thanks.

**Comment by EminGT** [comment]
Yeah no worries I understand.

Some other colored lighting implementations (like Bliss' one) completely throw away the actual lightmap of the game, and that causes a bunch of other problems that Complementary doesn't have.

The third one isn't specifically caused by the lighting being optimized for specific block types, but rather caused by some situations just being too hard to get calculations right for, especially when you add unsupported new modded blocks to the scene

**Comment by J-Naw** [comment]
Awesome thanks for the quick explanation. 

I'm in the process of adding block id's to euphoria's block.properties database incase it might fix it. 

Is there a way I can add these into the current code just for testing purposes? Instead of waiting for a new compiled jar from them? I assume just adding the id's to the current block.properties file?
