### ISSUE TITLE
Waving Vines Clip Into Blocks

### ISSUE THREAD

**Issue by IAGOnDiscord** [ComplementaryDevelopment/ComplementaryReimagined#18]
When Waving Leaves (not Waving Foliage, somewhat confusingly) is enabled, vines will occasionally clip into the blocks they're placed on as part of their animation. See below for a still frame of vines clipping into a tree they're attached to.
![image](https://user-images.githubusercontent.com/122576313/235319616-4ab3575b-3f50-4836-9e58-1ea43e93af5a.png)
A solution could be to make vines affixed to (solid) blocks not wave at all.

**Comment by EminGT** [comment]
This can't be fixed unfortunately. We can't detect vines that are next to solid blocks. This is why the option is disabled by default

**Comment by IAGOnDiscord** [comment]
Fair enough.
