### ISSUE TITLE
Player Shadows?

### ISSUE THREAD

**Issue by JupiterboyLuffy** [ComplementaryDevelopment/ComplementaryReimagined#19]
I would like it to where your player has a shadow.

**Comment by IAGOnDiscord** [comment]
The player already has a shadow.

**Comment by EminGT** [comment]
On Iris, player shadows are always enabled. On Optifine, you need to enable "Entity Shadows" in shader options -> main performance settings

**Comment by JupiterboyLuffy** [comment]
I meant to post this in Rethinking Voxels. Oops
