### ISSUE TITLE
Shadows on Handheld Items Don't Respect Pixel Shadows Setting

### ISSUE THREAD

**Issue by IAGOnGithub** [ComplementaryDevelopment/ComplementaryReimagined#20]
Self-explanatory. When the pixel shadows setting is set to anything other than OFF, shadows cast onto handheld items are not pixelated. This is most prominent with shields as they're large and flat, but it does affect other handheld items as well. Is this behavior intentional? If not, can it be fixed?

![no pixel shadows](https://user-images.githubusercontent.com/122576313/235333329-bdc23bbc-29d2-4945-a821-fe0a28ced564.png)
Note that any appearance of pixelated shadows on the shields is artifacting.

This is on Iris version 1.6.1, Minecraft version 1.19.4.

**Comment by EminGT** [comment]
Pixelated shadows are intentionally disabled on held items as they look really weird when enabled. Maybe I can try a different method later

**Comment by EminGT** [comment]
Closing this for now as it's too hard to make it work. I think I should spend the development time on more exciting stuff instead unless this gets reported by more people in the future
