### ISSUE TITLE
Handheld Items Cast Shadows Onto Themselves

### ISSUE THREAD

**Issue by IAGOnDiscord** [ComplementaryDevelopment/ComplementaryReimagined#21]
Related to #20. Self explanatory.
Look at the shield in the player's left hand. There is a shadow cast onto it by itself.

![shield casts shadow onto itself](https://user-images.githubusercontent.com/122576313/235333449-87cd7060-eea3-4a94-b45e-75148c932a26.png)

I labelled what I believe each part of the shadow is.

![labelled](https://user-images.githubusercontent.com/122576313/235333844-c49ee1f1-15b1-4e73-a6a5-0c2cecd85355.png)
(Green is supposed to be the player. I have no idea why the label disappeared.)

This is on Iris version 1.6.1, Minecraft version 1.19.4.

**Comment by EminGT** [comment]
I don't think this can be ever fixed without removing shadows on hand completely
