### ISSUE TITLE
Water color is off when using custom biomes

### ISSUE THREAD

**Issue by yannicksuc** [ComplementaryDevelopment/ComplementaryReimagined#23]
Hello !
Would it be possible to add an option for the water to match better it's hexadecimal value.

I've created a bloody/red water using a datapack and the color is off with the shader.
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/25967079/719fa980-af72-4f60-90b7-f4543aca1dd9)
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/25967079/b1c34d96-d793-488a-81e8-426835428816)

Here is the datapack for testing :
[datapack-colored-water.zip](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/files/11522676/datapack-colored-water.zip)

**Comment by EminGT** [comment]
I get "Data pack validation failed" error when I try to use the test pack for some reason. Might be an mc version mismatch?

**Comment by EminGT** [comment]
Will be fixed in the next version
