### ISSUE TITLE
Emissive Armor Trims

### ISSUE THREAD

**Issue by Crystalline1227** [ComplementaryDevelopment/ComplementaryReimagined#26]
It would be great to have an option to have emissive armor trims, e.g. XXVI's Shiny Armor Trims. Currently, Iris has no possible way to use the vanilla core shader needed to use the feature with Complementary. By implementing this feature into the shader itself, it bypasses that limitation.

Example of feature below:

https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/136302862/c146123a-f71d-4eed-b029-50d8883829e9

**Comment by EminGT** [comment]
Making all armor trims emissive wouldn't be well recieved by the community, but you can do it for the trims you want by using labPBR resource pack standard

**Comment by Crystalline1227** [comment]
Would it not work under the same toggles as emissive ores and glowing lapis blocks? Being toggleble by an individual player?
