### ISSUE TITLE
Colored lights

### ISSUE THREAD

**Issue by ghost** [ComplementaryDevelopment/ComplementaryReimagined#27]
I have zero knowledge in GLSL.
Is there any plan to implement colored lights or a port from other shader like Rethinking Voxels?

I doubt mid-range machine can handle that shader, even at 1080p despite already being faster than PTGI.

**Comment by EminGT** [comment]
Not many plans for now, as there doesn't seem to be any methods without huge drawbacks. But in the future I might just add a simpler method with drawbacks anyways

**Comment by Thefatsparrow** [comment]
you just use iris's floodfill coloured light a shader called photon uses it and that performs extremely well with coloured lighting enabled

**Comment by EminGT** [comment]
I'm aware of Photon but it isn't really viable to copy what it's doing to Complementary; mainly because it breaks Optifine support which more than half of the playerbase uses, and the feature isn't really "that" good to justify that

**Comment by Thefatsparrow** [comment]
well using floodfill lighting isn't copying photon if its a feature and you could just make it an iris only feature and say only enable on iris i see no problem with that

**Comment by EminGT** [comment]
I would do that if it was that simple to do

**Comment by Thefatsparrow** [comment]
https://www.geeksforgeeks.org/flood-fill-algorithm/

looks easy enough

**Comment by EminGT** [comment]
Sure. As if the problem was knowing how flood fill works

**Comment by EminGT** [comment]
Advanced Colored Lighting will be available in the next version
