### ISSUE TITLE
Caustic noise shape option

### ISSUE THREAD

**Issue by g6d3np81** [ComplementaryDevelopment/ComplementaryReimagined#29]
I was trying to determined if the shader have caustic or not, wasted half an hour before looking into the code.
It is subtle, thought it was shadow artifact at first. While this looks good at all depth level, I kind of hoping for the crispiness in shallow water.

An option to change noise parameter or type would be nice addition. Last improvement/suggestion I can think of without stepping into any ray tracing.

The shader right now is already great enough, achieving its goal being an easy choice for wide range of machine spec.

**Comment by EminGT** [comment]
It currently depends on the Water Style option. I can seperate it to a different option though

**Comment by EminGT** [comment]
"Water Caustic Style" option and a rebalance of Fantasy caustics are coming in the next version. Feel free to make a new post if you have any suggestions after the r2.3 update releases
