### ISSUE TITLE
Sun/Moon is invisible 

### ISSUE THREAD

**Issue by dopadream** [ComplementaryDevelopment/ComplementaryReimagined#3]
![image](https://user-images.githubusercontent.com/68942129/192520600-237bf08d-e64b-4158-a962-87801aaa2f1d.png)

**Comment by Warshipcito** [comment]
Go to your minecraft settings and enable the setting sun to yes, maybe that's because the sun/moon aren't enabled :)

**Comment by dopadream** [comment]
> Go to your minecraft settings and enable the setting sun to yes, maybe that's because the sun/moon aren't enabled :)

it was enabled

**Comment by EminGT** [comment]
I haven't seen anyone else have a similar issue. Maybe try with no resource packs and reset your game settings
