### ISSUE TITLE
Eyeshine in some animals (Tapetum lucidum)

### ISSUE THREAD

**Issue by g6d3np81** [ComplementaryDevelopment/ComplementaryReimagined#32]
Let me start by saying I don't even know if this even worth development time or within the scope of this shader.
I might do some mock-up in blender to see if the result really worth anything, for now, just an idea and discussion.

Did a quick still image mock-up with wolf.
![tapetum_simulated_](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/120431210/e768cf21-04f0-4f8a-99d4-b464cbe27c21)

Spider already have emissive texture... all the time... regardless. I'll leave that for another time.

![tapetum_simulated_fig_](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/120431210/f09c0caa-6f16-4a81-928d-275057ba7b17)
Don't know if optifine or iris (PBR workflow) have a way to do it, or if an extra resource pack is needed.
The idea is to alter mob texture to be emissive under conditions...
- Night time? (or possibly under low light)
- Player holding light (maybe with dynamic light enabled)
- Mob facing player within certain degree (calculate emissive from camera normal?)
  luckily wolves like to look at player so it can be visible quite often, not sure about cats.

I see this is an interesting concept I never see in any shader, maybe because it is over engineering. Or just [too distracting](https://www.reddit.com/r/Damnthatsinteresting/comments/nkp0qs/sheep_eyes_at_night/) generally.
Probably taking away the vanilla aesthetic, which is bad if that is what the shader is aiming for.

**Comment by EminGT** [comment]
It's definitely possible, and not too hard to do either. But I don't think an overwhelming majority of people are going to like this
