### ISSUE TITLE
LaserIO Render Glow

### ISSUE THREAD

**Issue by quikenb** [ComplementaryDevelopment/ComplementaryReimagined#33]
Initially placed on LaserIO https://github.com/Direwolf20-MC/LaserIO/issues/184#issue-1775908950

Shaders Version
Complementary Reimanigend_r2.2

Oculus Version
1.6.4

Rubidium Version
0.6.5

LaserIO version
1.6.1

Minecraft Version
1.20.1

Forge Version
47.0.19

Modpack & Version
ATM9 V0.0.15

Do you have optifine installed?
I have other rendering based mods installed

Describe the issue
LaserIO transfer lasers have immense green glow

Steps to reproduce
Use complimentary shaders and the issue is right there.

Expected behaviour
No green glow. As well as the laser lines showing

Screenshots
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/18548078/75ab8ced-e368-4787-aea7-90228fe77406)

How it's supposed to look
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/18548078/ed796350-c444-4b2f-821e-a69c2bbdae86)

Log files
https://pastebin.com/8D40ugJ9

Additional information
No response

**Comment by EminGT** [comment]
As Direwolf mentioned in the LaserIO thread, this is a shader *mod* issue, not a shader *pack* issue. These kind of issues usually can't be fixed on the shader pack side but can be fixed very well on the shader mod side.

**Comment by mikerooni** [comment]
I'm not sure if this is relevant in any way, but somehow the render glow vanishes when using Complementary Reimagined. But so do the connection lines, making it even more unusable, unfortunately.
