### ISSUE TITLE
Puddles are rendered under glass blocks

### ISSUE THREAD

**Issue by terzag** [ComplementaryDevelopment/ComplementaryReimagined#34]
Hello,
When having rain puddles enabled in ComplementaryReimagined settings, they appear under glass blocks. Which is a bit annoying when using glass ceilings: https://imgur.com/a/OIMci8q

Using CR 2.2 with Iris 1.6.4/Sodium 0.4.10 on Fabric/Minecraft 1.20.1. Linux (Xubuntu 23.04) with an AMD Radeon RX 6500 XT GPU.

I'm not sure if it's related to the way Minecraft handles glass/transparent blocks and if it's fixable? Or even if it's a bug in Iris rather than CR.

**Comment by EminGT** [comment]
It's something Iris or Optifine need to give us a way to fix, because right now every single shaderpack in existence has this problem if it has puddles

**Comment by terzag** [comment]
I see. So, that's a more general issue than I thought. Thanks for the clarification.
