### ISSUE TITLE
Complementary Reimagined looks MUCH brighter on Iris than on OptiFine

### ISSUE THREAD

**Issue by Atirtra** [ComplementaryDevelopment/ComplementaryReimagined#35]
The images speak for themselves. First image is Iris, second one is OptiFine.
Is this intended, if CR utilizes some features of Iris? Modrinth page clearly states that both platforms are supported, so it feels wrong to have the shaders look this different on each of them. Complementary v4 looks identical on them though.

![2023-07-11_05 05 32](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/110634509/5c25bb93-9576-42b6-8cd0-683eada402cd)
![2023-07-11_05 07 30](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/110634509/ad7d0f6b-4d65-4e85-a8a5-e1f5afc22ebb)

**Comment by EminGT** [comment]
This isn't intended. I don't know why they are different. Will test when I can

**Comment by EminGT** [comment]
Will be fixed in the next update
