### ISSUE TITLE
Farmer's Delight Crop Support

### ISSUE THREAD

**Issue by MythrilBagels** [ComplementaryDevelopment/ComplementaryReimagined#36]
Hi there,
This is a simple and straightforward suggestion, requesting integration with Farmer's Delight's Crops and Wild Crops, to be rendered the same way as other crops, and flowers.

**Comment by EminGT** [comment]
Thank you for the suggestion, but adding support for thousands of mods with a million of different block IDs is not something I want to start working on. There are so many popular mods out there that I would need to work 24/7 for years to complete mod support, and the ever-changing nature of the Minecraft mod industry would punish me with even more work every day. Not to mention the shaderpack getting slower and slower to run with the amount of extra checks reaching insane numbers for any computer to handle after a certain point. So I hope you understand why I don't want to start on specific modded block support
