### ISSUE TITLE
[suggestion] implementing glowing ores

### ISSUE THREAD

**Issue by ColonelGerdauf** [ComplementaryDevelopment/ComplementaryReimagined#37]
I had a thought about having ores, particularly non-vanilla ores, glow in the right pixels.

By picking blocks registered as an "_ore", you can get a general average colour, more specifically the colour of the stone type holding the ore. 
Then, you can map pixels where the colour is far in hue from the average, and have them glow in the colour of the individual pixels (or maybe the average of the deviant colours).

**Comment by EminGT** [comment]
That's good food for thought. I think I could instead get the average of the edge-pixels of the texture, which I think should give us the stone color for like 99% of the modded ores

**Comment by ColonelGerdauf** [comment]
Edge-pixels can certainly do the job. I hope then that a mod doesn't make some kind of "rimmed ore block", because that would be awkward for multiple reasons.

**Comment by EminGT** [comment]
Ah, there are resource packs that do outlined ores aren't there. Maybe we move one pixel to the center and then sample the edge-pixels from there. This will probably hit some ore pixels again but it should be close-enough to the stone color I think. I will experiment

**Comment by EminGT** [comment]
Okay I think I put together something decent. It's not perfect but it should be good enough. Will be in the r2.3 update

**Comment by ColonelGerdauf** [comment]
I wonder if there is a particularly fast and efficient way to get the most common colour of the block face. There tends to be more rock pixels than ore pixels.

Then get the pixels that are close enough to the most common, and average all of them together.
