### ISSUE TITLE
[Feature Request] More Fog Settings

### ISSUE THREAD

**Issue by GhostIsBeHere** [ComplementaryDevelopment/ComplementaryReimagined#39]
I'd like to be able to specify a fog start and end distance in the config please! Preferably with separate settings for overworld, nether, end, and underwater, although that's not too big of a deal.

**Comment by EminGT** [comment]
There is no starting distance for any kind of fog in Complementary Reimagined, but there are already settings for the (end) distances of Atmospheric Fog and Water Fog separately. Nether and End options might be added later

**Comment by GhostIsBeHere** [comment]
Ah. I was wanting to make my fog look more like that of [Fog Looks Good Now](https://modrinth.com/mod/fog-looks-good-now-fabric), but I guess that isn't possible. Would love to see that possibility added :)

**Comment by EminGT** [comment]
You should be able to get quite close with correct settings
