### ISSUE TITLE
Glowing on the top surface of all dropped items

### ISSUE THREAD

**Issue by Bobmarlinjr** [ComplementaryDevelopment/ComplementaryReimagined#41]
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/48042415/573476a3-9fc7-4a3d-a881-abd83d6cd9b0)

Appears with any combination of optifine and Complementary, with labPBR setting turned on. Playing on 1.12.2 with forge

**Comment by EminGT** [comment]
The Discord community concluded that it's caused by a mod, but I don't know which mod it is. I don't think it's fixable on the shader-side
