### ISSUE TITLE
Entities and players becoming emissive at certain angles

### ISSUE THREAD

**Issue by Kennylotl** [ComplementaryDevelopment/ComplementaryReimagined#42]
For some reason, when using the 5.0.1(Iris) version of these shaders, entities and players can become emissive, seemingly when the camera is at certain angles or in certain positions.

![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/127928680/04d3a937-81d9-4cbb-b534-30706c8a5e70)
On the left, there's how a player looks normally.
On the right, there's that same player with the lighter parts of their skin glowing.

This also happens to my own character, though I didn't think to get a screenshot of it. It happens both in third person and with the first person hand

**Comment by EminGT** [comment]
This is an Iris issue. It will be fixed with the upcoming Iris update, or
if you switch to Optifine
