### ISSUE TITLE
Aether always looks like nighttime

### ISSUE THREAD

**Issue by TheGag96** [ComplementaryDevelopment/ComplementaryReimagined#46]
With Complementary Shaders Reimagined on, the Aether always appears to be nighttime, even though (at the beginning) it's supposed to always be day.

![2023-09-29_18 17 35](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/2746019/cd2bf541-fc05-419d-aa23-7b43bc566488)

**Comment by EminGT** [comment]
That's weird. Does it work with any other shaderpack (like BSL), or Complementary v4.7.2?

**Comment by TheGag96** [comment]
> That's weird. Does it work with any other shaderpack (like BSL), or Complementary v4.7.2?

I tried v4.7.2 and it doesn't happen there.

**Comment by EminGT** [comment]
Might be fixed in the next update (r5.1)

**Comment by EminGT** [comment]
Fixed in r5.1
