### ISSUE TITLE
[Request] Adding a range slider for waving leaves/objects.

### ISSUE THREAD

**Issue by Kathezel** [ComplementaryDevelopment/ComplementaryReimagined#47]
Because of a mod called "Bobby" that is increasing my randerdistance I play with 40 Chunks rendert.
I also have *waving leaves* active and all other waving settings.
If huge forests gets rendert all of the tress are waving even if they are 20-30+ chunks away. I can only see it by zooming in, but still they're waving but it's really not necessary.

It would be really nice to have a slide to change the range for the waving leaves/objects *X* amount of chunks away, that they don't wave anymore and save up resources of the PC.

So players like me can have waving leaves and huge renderdistance plus no framerate loss. :D

**Comment by EminGT** [comment]
The waving effect doesn't even cost 0.1% fps so there really isn't any resources to save here
