### ISSUE TITLE
Nether border fog is capped at 16 chunks of render distance

### ISSUE THREAD

**Issue by Atirtra** [ComplementaryDevelopment/ComplementaryReimagined#49]
Exactly as the title says, nether border fog doesn't scale past 16 chunks at all. At both render distances of 32 and 16, the fog looks exactly the same. The fog of Complementary V4 and Reimagined V2.3 scaled all the way up to 64 chunks in the past, but now the new Reimagined nor Unbound don't.

I'm not sure if this is intended as Vanilla doesn't allow far border fog in the nether either, but I would be happy with an option to change the fog render distance freely. Thanks

**Comment by EminGT** [comment]
"Nether View Limit" setting will be added in the next update (r5.1)
