### ISSUE TITLE
Warped Logs lose their emission when getting farther away

### ISSUE THREAD

**Issue by Atirtra** [ComplementaryDevelopment/ComplementaryReimagined#5]
Warped logs aren't emissive from far away.
Crimson logs don't have this issue as you can see from the image.
Complementary v4 didn't have this problem.

https://user-images.githubusercontent.com/110634509/209586325-91338ee7-e941-4052-842c-182e5f9f7a24.png

**Comment by EminGT** [comment]
Thank you. Looks like I need to tweak some variables

**Comment by EminGT** [comment]
Fixed in Reimagined r2.0 (soon to be released)
