### ISSUE TITLE
Feature Request: Curio/Trinket support for dynamic lighting

### ISSUE THREAD

**Issue by son0fether** [ComplementaryDevelopment/ComplementaryReimagined#51]
Hello there, this is a fantastic shader and I love it.

I particularly appreciate the built-in very fast dynamic lighting from the off-hand slot.  Would it be too much trouble to include curio and trinket slots for dynamic lighting as well?
* https://www.curseforge.com/minecraft/mc-mods/curios (forge)
* https://www.curseforge.com/minecraft/mc-mods/trinkets (fabric)

This might involve querying the curios/trinkets mods at startup for which slots exist.  I'd understand if that would be too much, but it would be really fun.

Example datapack that lets you put a torch on your head with Curios:
data/curios/tags/items/head.json -> { "values": [ "minecraft:torch" ] }

For dynamic lighting mods, the following mod provides a solution, but it looks like a shaderpack with dynamic lighting would have to add the change itself:
* https://www.curseforge.com/minecraft/mc-mods/radiant-gear
* https://github.com/illusivesoulworks/radiantgear/issues/13

**Comment by EminGT** [comment]
Shaders unfortunately can't detect any inventory slots other than the current held item, and the off-hand item. So there isn't anything I can do to implement this
