### ISSUE TITLE
Incorrect «Display Entity» Rendering

### ISSUE THREAD

**Issue by ObscuriaLithium** [ComplementaryDevelopment/ComplementaryReimagined#52]
When switching between light-emitting and normal items in your hand (and sometimes without light-emitting items), Block Displays become glowing. They keep changing the rendering almost every time you switch the item in your hand. This also happens with Item Displays and Text Displays.

Fabric 1.20.1, Reimagined r5.0.1

![IMG_20231106_150002_219.png](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/100697103/0c066011-8123-46df-8d2f-22f1c3749a54)

![IMG_20231106_150005_838.PNG](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/100697103/41e31c09-7494-4074-bd0a-98cda33c3b7f)

**Comment by EminGT** [comment]
Try updating your Iris and Sodium. You are using outdated versions

**Comment by ObscuriaLithium** [comment]
It works, thanks!
