### ISSUE TITLE
cloud bug

### ISSUE THREAD

**Issue by Thefatsparrow** [ComplementaryDevelopment/ComplementaryReimagined#53]
clouds be buggin when shadows appear on them 

they vanish and come back and just cause alot of visual glitches i am using terralith and am on the skylands biome

also im on version 5.0.1 and using sodium version 0.5.3 and iris version 1.6.10

also theres a screenshot of the f3 menu if thats helpful
![2023-11-10_12 06 30](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/86117177/c558f5b9-0498-4930-aa55-c86918eb02e6)
![2023-11-10_11 56 31](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/86117177/20b6ae2f-3efe-448e-a511-998c000c3468)
![2023-11-10_11 56 34](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/86117177/7bd76b35-fc8d-49d7-bde7-122a33ff17b1)
![2023-11-10_12 09 03](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/86117177/2d367e81-6a4a-4a64-95e7-4637bf59d9b9)
![2023-11-10_12 19 15](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/86117177/2bc2c305-3104-4a18-b654-a215fa6e50e1)
![2023-11-10_13 32 48](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/86117177/af333fea-528b-48ab-935d-2856718c82f0)

**Comment by Thefatsparrow** [comment]
also im on version 5.0.1 and using sodium version 0.5.3 and iris version 1.6.10

**Comment by EminGT** [comment]
The "Prevent Clouds in Interiors" feature causes this side effect, and there isn't really a way to fix it. All you can do is disabling the feature in shader settings
