### ISSUE TITLE
Weird Fog when using Fabric Skybox with Hyper Realistic Skies

### ISSUE THREAD

**Issue by Vaskyy** [ComplementaryDevelopment/ComplementaryReimagined#56]
At the beginning im just changing the time without additional skybox enabled, and its looks perfect 🙂
But when enabling Fabric Skybox (at 0:22) with Hyper Realistic Skies the weird black bars appear at some times, and the sky changes are very sudden.
I talked to the maker of the Skybox Resource Pack (UsernameGeri) and he sent me here to report this behavior.
Or is this an weird setting that i have to change to let it look normal again?
Appreciate all the help 🙂

[Video about the Issue](https://www.youtube.com/watch?v=hTl6OjTAAtc)

UsernameGeri also posted his own screenshots that show the weird Fog Behaviour:
[Discord Message Link](https://discord.com/channels/744189556768636941/975340372865744937/1177000849738846279)

**Comment by Vaskyy** [comment]
without skybox
![without skybox](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/10385142/07d47076-a7a1-461f-8ecc-ee442779d439)
with skybox enabled
![with skybox enabled](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/10385142/3b963efe-049b-4cd3-b114-328a10b5de6f)

**Comment by UsernameGeri** [comment]
After further testing, I determined that this issue only affects versions above ComplementaryShaders_v4.7.2. Both Unbound and Reimagined.

Since many of the sky options very removed from newer versions, I cannot confirm if this is a config issue, or if something broke with the mod.

**Comment by UsernameGeri** [comment]
Well, there 2 significant mods that adds custom sky support, those being fabricskyboxes and optifine, not a whole lot of options there. As I mentioned in a comment above, this didn't use to be an issue with older versions of the shader.
