### ISSUE TITLE
further water caustics customization

### ISSUE THREAD

**Issue by motyI** [ComplementaryDevelopment/ComplementaryReimagined#58]
We have the ability to choose between the unbound and reimagined caustic styles, but both look a bit wonky and are too sharp while underwater. It would be nice to have the ability to tweak the opacity of caustics. In complementary v4 you could also turn projected caustics on/off, and this option is missing from unbound. 

Also, this could be personal preference, but I loved the way water caustics looked in v4, and now both available options just don't look nearly as good, so having the third (old) one would be great

**Comment by EminGT** [comment]
Sorry. You are the only person I have seen that prefers the old caustics, so I don't really want to spend development time on something that the majority of people are really happy with.
