### ISSUE TITLE
water texture is not affected by waves / waves are too short

### ISSUE THREAD

**Issue by motyI** [ComplementaryDevelopment/ComplementaryReimagined#59]
Idk if this is a suggestion or a bug, but unlike in v4, the vanilla water texture doesn't seem to move with waves. It's completely flat, and this might just be because the wave bumpiness is not customizable, which is another thing present in v4 but absent in unbound

Complementary v4.7.2:

https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/83429505/5cdd3b90-a2f6-4ada-ae95-8b6035f88e07

Complementary Unbound v5.1:

https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/83429505/618aebeb-7fbb-4e95-bf63-849580868d17

**Comment by EminGT** [comment]
You simply disabled the Waving Water Texture option

**Comment by motyI** [comment]
I just checked, and I had it enabled. I also played around with some settings a bit, and no matter what options I pick, the waves are barely noticeable. Unbound / unbound + waves / reimagined, waving water texture on / off, wave strength, wave size - all of those options barely do anything when it comes to the waves' magnitude and bumpiness.
