### ISSUE TITLE
Clouds visible through waning blindness effect

### ISSUE THREAD

**Issue by RephlexZero** [ComplementaryDevelopment/ComplementaryReimagined#6]
![2023-01-10_01 25 08](https://user-images.githubusercontent.com/67481201/211441181-33b070aa-c289-4b80-9232-8f124816f91f.png)

To reproduce just give yourself the blindness effect and wait for it to wear off.
Quilt Iris, Nvidia on Linux.

**Comment by EminGT** [comment]
Doesn't happen on my end. The clouds appear at the exact time blindness goes away

**Comment by RephlexZero** [comment]
Without shaders this issue is still present, so I guess it counts as vanilla behaviour even though it doesn't make the most sense.
The clouds appear as the blindness transition starts,  yes. My bad.

**Comment by EminGT** [comment]
No problem thanks for taking your time anyways
