### ISSUE TITLE
wrong shadow?

### ISSUE THREAD

**Issue by motyI** [ComplementaryDevelopment/ComplementaryReimagined#60]
I'm no expert in shadows, but I think my head's shadow should not be split in 3 when looking down
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/83429505/5ddcd1e8-08f6-4d22-b7e3-66ff637c7739)
It's not affected by any of the sun or shadow options

**Comment by EminGT** [comment]
This needs to be this way in order for the sun/moon lighting to be able to work correctly in caves. It's a technical limitation
