### ISSUE TITLE
Please make rainy/snowy sky completely overcast

### ISSUE THREAD

**Issue by Crossover661** [ComplementaryDevelopment/ComplementaryReimagined#63]
I really like this shader (it is my favorite of all the shaders I've tried), but rainy and snowy weather looks a little weird in recent versions.

In newer versions of Complementary Reimagined, rainy and snowy weather increases the cloud cover slightly and darkens the sky but does not make the sky overcast as seen in previous versions. Even if I set the "rain cloud addition" in Unbound Cloud Settings to the maximum, the sky is not overcast. With default settings, the sky looks as though it's partly cloudy at sunrise/sunset.

By contrast, in version 2.3 the sky is completely overcast during rainy or snowy weather, and visibility is reduced, making it look more realistic (bottom screenshot), however the overcast sky looks a little too "blue".

![2023-12-13_23 38 40](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/90175413/7c55b244-9583-48d3-a40d-0a3501eb25ba)
![2023-12-13_23 37 59](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/90175413/4522f5d2-c410-4a62-b229-7ada6d84b2e0)

**Comment by Crossover661** [comment]
Also, if you can, I would suggest adding colored light using an HSV (hue-saturation-value) or RGB system, and having a config file for the colors of various light sources.

**Comment by djmrFunnyMan** [comment]
> Even if I set the "rain cloud addition" in Unbound Cloud Settings to the maximum, the sky is not overcast

This doesn't seem true I can make the sky pretty overcast
![2024-03-11_15 07 15](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/68905776/5c467c60-a375-42af-a894-fe06d4c4d644)

**Comment by djmrFunnyMan** [comment]
But yes I do think the default values should be higher

**Comment by EminGT** [comment]
"Heavy & Colder" rain style option will be added in the next version
