### ISSUE TITLE
[problem] with water reflections

### ISSUE THREAD

**Issue by scoruluce-studio** [ComplementaryDevelopment/ComplementaryReimagined#64]
I am with the preset "ultra".

https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/97796239/d87f270b-60e8-4e58-854a-c9a09a1816e5

**Comment by EminGT** [comment]
Sorry. I'm personally also bothered by this problem a lot but there isn't much that can be done about it. It's a limitation of screenspace reflections, and there isn't a good alternative to this reflection method in Minecraft at the moment. Best you can do is using the Unbpund water style setting to make the problem way less noticeable during gameplay.
