### ISSUE TITLE
[Suggestion] Add support for colored lights

### ISSUE THREAD

**Issue by RobotoSkunk** [ComplementaryDevelopment/ComplementaryReimagined#69]
Complementary lightning is pretty good, but it would be much better if there are colored lightnings to make the game look pretty good.

This is a screenshot from Iris devs.
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/49355293/83ddb7e0-e580-4d52-bad4-66779c5af9d9)

I tried BSL shaders to test how these colors are calculated, and I think that there's something related with the camera because the lightning colors defaults to the classic lightning color if the block is not visible by the camera.

**Comment by EminGT** [comment]
Just get the Euphoria Patches add-on for Complementary and you will have the same colored lighting option as BSL
