### ISSUE TITLE
Excessive flickering around lava

### ISSUE THREAD

**Issue by CalebAShepherd** [ComplementaryDevelopment/ComplementaryReimagined#7]
Light emitting from lava flickers quite a bit when using advanced light propagation.

**Comment by EminGT** [comment]
Advanced light propagation is not a feature in Complementary Reimagined. This isn't the Rethinking Voxels repository

**Comment by EminGT** [comment]
Advanced light propagation is not a feature in Complementary Reimagined. This isn't the Rethinking Voxels repository
