### ISSUE TITLE
Add more options for water rendering? Suggestion

### ISSUE THREAD

**Issue by Dreig-Michihi** [ComplementaryDevelopment/ComplementaryReimagined#71]
In Complementary V4 you could disable all reflections except sky and clouds, but in latest versions the only option we have - just disable water rendering, so it looks like without shaders at all.
And also disabling reflections for certain block types.

Watch what amazing look I got with Complementary V4:
https://youtu.be/DybwhyPuP0E

I can't make the same water now sadly! And Ice always has reflections too 😢 

Why I prefer to disable reflections - it's because of this kind of bugs:
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/60939608/cf6b00d0-134a-4aec-ae99-21fb9876a4f3)

**Comment by EminGT** [comment]
Added in r5.2
