### ISSUE TITLE
Glowing Particles options Suggestion

### ISSUE THREAD

**Issue by Dreig-Michihi** [ComplementaryDevelopment/ComplementaryReimagined#72]
Flame and Soul Flame particles don't glow immidiatly, they start glow only after some time.
Could you add some option, which would toggle, if a particle starts glowing from start?

Fire particles glow badly, I'd like it glow like in lighted area
[https://youtu.be/99vSfVAgNqU](url)

**Comment by EminGT** [comment]
That's on the game for not lighting up the particles at first. The shader can't change this
