### ISSUE TITLE
The problem with lime wool

### ISSUE THREAD

**Issue by Sergo467** [ComplementaryDevelopment/ComplementaryReimagined#78]
I tested it on forge and on fabric, but with certain settings, lime wool looks like this, here is the settings file.
[ComplementaryUnbound_r5.1.1.zip.txt](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/files/14063093/ComplementaryUnbound_r5.1.1.zip.txt)
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/67155404/bc45e69a-7d46-4024-8178-99b77dbb0ef7)
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/67155404/84cdb6c3-c8a5-492d-8501-426c7d6adb80)

**Comment by EminGT** [comment]
Video Settings -> Shaders -> Shader Settings -> Materials -> IntegratedPBR -> somewhere in there there is a "Green Screen Lime Blocks" option. Disable it
