### ISSUE TITLE
  Crash on 1.20.1 complementary unbound 5.1.1

### ISSUE THREAD

**Issue by Cookieess** [ComplementaryDevelopment/ComplementaryReimagined#79]
If I turn on the shaders after a few seconds it will crash my game. There is no crash report. This happens with every version of complementary but not rethinking voxels.

Console spams this error:
[17:44:42] [Render thread/ERROR]:
 ########## GL ERROR ##########
[17:44:42] [Render thread/ERROR]:
 @ Render
[17:44:42] [Render thread/ERROR]:
 65539: Invalid key -1

**Comment by EminGT** [comment]
Shaders can not crash a game unless the drivers/game/other software make a mistake
