### ISSUE TITLE
wrong sky reflections using specular maps

### ISSUE THREAD

**Issue by motyI** [ComplementaryDevelopment/ComplementaryReimagined#81]
Instead of reflecting the sky/fog, handheld blocks use the brightness of wherever the player is standing. This works in most cases, but when reflecting, for example, distant objects while being under a roof / under trees, it looks like if the sky was really dark, while the rest was sunlit.

Video:
https://imgur.com/a/tFEW5ZG

**Comment by EminGT** [comment]
This can't be fixed for technical reasons unfortunately. It's there to prevent issues like held items reflecting brightly inside closed areas like caves
