### ISSUE TITLE
Disable glow on certain blocks

### ISSUE THREAD

**Issue by rotkudnoK** [ComplementaryDevelopment/ComplementaryReimagined#82]
Is it possible to disable glow on certain blocks or maybe configure the intensity? Some modded blocks have a very strong glow when powered and I find it really out of place.
Here's an example
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/17196454/a715337f-7136-4407-bb5a-849f38b62bec)

**Comment by EminGT** [comment]
The shader can't disable a glow that it doesn't add itself. The glowing block you are seeing seems to be glowing because of a mod incompatibility
