### ISSUE TITLE
TAA looks weird in 5.1.1

### ISSUE THREAD

**Issue by kikawaa** [ComplementaryDevelopment/ComplementaryReimagined#83]
In latest version of shader (5.1.1) TAA has ghosting effect unlike previous versions, which makes it look much worse, please fix that or rollback changes made to TAA in that version, here is example that there is no blur/ghosting in 5.0.1:
![501](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/155401346/6bf8c5be-b146-44cc-bf23-3a0859764af5)
and this is how it looks in 5.1.1 you can clearly see that it looks blurry in this version:
![511](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/155401346/5984fb73-7c63-4162-9895-1056c5e32785)
I know that ghosting is normal behavior for TAA, but it wasn't like that in previous versions of shader, so please fix it.

**Comment by EminGT** [comment]
Are you 100% sure that you are using the exact same settings in these two?

**Comment by EminGT** [comment]
This will be improved upon in r5.2. Feel free to open a new bug report if you find clearly problematic examples in that version as well
