### ISSUE TITLE
Weird grid lines with glass (tested with Reimagined style using Iris)

### ISSUE THREAD

**Issue by mrjasonn** [ComplementaryDevelopment/ComplementaryReimagined#88]
Glass shouldn't really have grid lines even when the textures are not connected (tested with Reimagined style using Iris):
![2024-03-07_21 20 39](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/120269221/1c52d051-ff1d-448b-b6aa-a825eb038151)

**Comment by EminGT** [comment]
Please show me the blocks that cause these shadows

**Comment by EminGT** [comment]
I don't see any issue here. If you want connected glass you use a connected glass mod
