### ISSUE TITLE
i play create , can Reimagined also easy to make zinc_ore glow as Complementary Version 4?

### ISSUE THREAD

**Issue by bAdOoWindy** [ComplementaryDevelopment/ComplementaryReimagined#9]
in version 4
just need to 
`block.11132=minecraft:iron_ore create:zinc_ore`
`block.11133=minecraft:deepslate_iron_ore create:deepslate_zinc_ore`
will make zinc_ore glow

in Reimagined not work

**Comment by EminGT** [comment]
Reimagined uses a bit different of a glow area detection for ores. I will look into making them work nicer when I sort out the higher priority things in the future

**Comment by EminGT** [comment]
A separate block.properties entry for modded ores have been added in a recent update
