### ISSUE TITLE
Volumetric Clouds are removed around the player in a weird shape

### ISSUE THREAD

**Issue by djmrFunnyMan** [ComplementaryDevelopment/ComplementaryReimagined#92]
Issue from discord added here for tracking.
When you're inside clouds they get removed when they're too close to you except instead of getting removed in an even sphere around your camera they get removed in whatever this shape is
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/68905776/ff938f51-78aa-4b13-8236-7ebb3c7455b1)
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/68905776/11e4459a-6698-4ac7-bc95-9ac270c786fb)

This looks quite wrong, and also you can see the clouds appear under you if you simply jump
![image](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/68905776/6d073c42-2f53-47cf-81c8-eca15e664dfb)

**Comment by EminGT** [comment]
I doubt this will ever be fixed to be honest. It's one of those "too much effort for too little reward" situations. Closing as "won't fix"
