### ISSUE TITLE
[Suggestion] Distance slider for volumetric cloud fog.

### ISSUE THREAD

**Issue by djmrFunnyMan** [ComplementaryDevelopment/ComplementaryReimagined#93]
I suggest adding a slider for how close to you volumetric cloud particles can get before they start fading away. Just like the one we already have for atmospheric fog.

Increasing the distance for example would be very useful as an alternative to "prevent clouds in interiors" as that setting has many jarring problems (which I assume are unfixable) and I would rather have it turned off.

**Comment by EminGT** [comment]
The cloud system doesn't really support this and I don't want to change it either because optimization :P
