### ISSUE TITLE
sky gets darker and more gray when skylight value is lower

### ISSUE THREAD

**Issue by Bobisjohn714** [ComplementaryDevelopment/ComplementaryReimagined#95]
the sky shouldnt get more gray and dark when in a place with little skylight, it should stay the same.
screenshots were taken after resetting the options in the shader menu.
the shader version is the latest one from github, downloaded using the "<>code" green button.

![2024-03-22_11 13 01](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/94441070/7e68cc86-17db-4865-a466-40a47e503756)
![2024-03-22_11 13 04](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/94441070/e914d150-4987-4ccb-948a-1073e33536ff)
![2024-03-22_11 13 13](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/94441070/f6bedf34-4af0-4d85-909f-7cc893583f1c)

**Comment by EminGT** [comment]
The problem is that you are at negative altitude. The cave detection kicks
in. There unfortunately isn't any other way to detect caves
