### ISSUE TITLE
Grainy lines in shadows on grass/wheat

### ISSUE THREAD

**Issue by ty-zi** [ComplementaryDevelopment/ComplementaryReimagined#97]
I am using default medium settings, in some lighting wheat and grass textures get a grainy appearance to the shadows on them. I have tried adjusting settings but have not been able to find something to fix this or disable the shadows on grass/wheat

![grainy shadows](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/83525402/c9d1bca9-c4a8-4123-a030-f8fd5760b5c5)
![grainy shadows2](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/83525402/d0542af4-3fbf-4b81-9ab9-f8bf9d4a85ed)

**Comment by EminGT** [comment]
Sorry this is just how it is with the current way things are set up
